# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - main # default branch

jobs:
  build:
    # 指定操作系统
    runs-on: ubuntu-latest
    steps:
      # 将代码拉到虚拟机
      - name: Checkout repository
        uses: actions/checkout@v3
      # 指定node版本
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # 依赖缓存策略
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      # 依赖下载
      - name: Installing Yarn
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install -g yarn
      # 打包
      - name: Running Add
        run: yarn
     # 打包
      - name: Running Build
        run: yarn build
      # 发布
      - name: Running Publish
        run: npm publish
        env:
          # NPM_TOKEN is access token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
